### ISSUE TITLE
Make a short writeup about the Circuit Protection

### ISSUE THREAD

**Issue by csinko** [csinko/io-master#11]
This will be put into the readme and be used for preliminary design presentations and discussions.

Cover what this component is responsible for, what it adds to the design of the project, and some challenges that will arise.  Also cover any preliminary design ideas that exist.

**Comment by nuntch** [comment]
Short write up about circuit board protection
Circuit protection is a crucial part of any device to help safeguard against unexpected and unplanned power issues. This is important to prevent injury to users, damage to the device and potentially fire. This will include having fuses, diodes, conformal coating, reverse polarity protection, over voltage protection and will protect against accidental grounding. 
Some challenges that may occur is due to the learning curve of designing the circuit protection circuit. Designing a circuit that can account for over voltage protection, short circuit protection, reverse polarity protection, etc and maintain a small footprint on a circuit board could prove to be difficult. Accounting for different/higher voltage levels used by the different protocols may become a challenge.
